version: '2'
services:
    osrc:
        image: php:rc-apache
        restart: always
        ports:
        - "10001:80"
        volumes:
            - "./osrc/:/var/www/html/"
            - "./flag:/flag"